version: '3'
services:

  server:
    build: .
    container_name: tasks-app
    ports:
    - "8000:8000"
    command: sh -c "cd /send_solution_test
             && alembic upgrade head
             && python main.py"
    env_file:
      - .env
    depends_on:
      - database
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  database:
    ports:
      - "5432:5432"
    image: postgres
    container_name: tasks-db
    env_file:
      - .env